### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by grray** [dominikschnitzer/musly#33]
I'm trying to build musly on Ubuntu 16.10. Got following error after `cmake ..`:
```
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibAV (missing: LIBAV_ROOT_DIR) (Required is at least
  version "0.8")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibAV.cmake:218 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:34 (find_package)
```

If i run it like this `cmake .. -DLIBAV_ROOT_DIR=/usr` then I get compile error
```
/usr/src/musly/libmusly/decoders/libav.cpp: In member function ‘virtual std::vector<float> musly::decoders::libav::decodeto_22050hz_mono_float(const string&, float, float)’:
/usr/src/musly/libmusly/decoders/libav.cpp:182:5: error: ‘AVCodecParameters’ was not declared in this scope
     AVCodecParameters *decp = st->codecpar;
     ^~~~~~~~~~~~~~~~~
/usr/src/musly/libmusly/decoders/libav.cpp:182:24: error: ‘decp’ was not declared in this scope
     AVCodecParameters *decp = st->codecpar;
                        ^~~~
/usr/src/musly/libmusly/decoders/libav.cpp:182:35: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’; did you mean ‘codec’?
     AVCodecParameters *decp = st->codecpar;
                                   ^~~~~~~~
/usr/src/musly/libmusly/decoders/libav.cpp:190:53: error: ‘avcodec_parameters_to_context’ was not declared in this scope
     avret = avcodec_parameters_to_context(decx, decp);                                                     ^
```
If i force this branch in code https://github.com/dominikschnitzer/musly/blob/master/libmusly/decoders/libav.cpp#L176, than it compiles successfully, but I don't know how to fix this properly for PR.

**Comment by grray** [comment]
Also I had to run ldconfig manually after build.

**Comment by f0k** [comment]
Hmm, maybe something is wrong with the version checks. The output of the following three commands would be useful to see:
```bash
ffmpeg -version
avconv -version
grep -rF '#define LIBAVFORMAT_VERSION' /usr/include/libavformat/
```

**Comment by grray** [comment]
```
$ ffmpeg -version
ffmpeg version 3.0.7-0ubuntu0.16.10.1 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 6.2.0 (Ubuntu 6.2.0-5ubuntu12) 20161005
configuration: --prefix=/usr --extra-version=0ubuntu0.16.10.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librubberband --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-chromaprint --enable-libx264
libavutil      55. 17.103 / 55. 17.103
libavcodec     57. 24.102 / 57. 24.102
libavformat    57. 25.100 / 57. 25.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 31.100 /  6. 31.100
libavresample   3.  0.  0 /  3.  0.  0
libswscale      4.  0.100 /  4.  0.100
libswresample   2.  0.101 /  2.  0.101
libpostproc    54.  0.100 / 54.  0.100
```
```
$ avconv -version
The program 'avconv' is currently not installed. You can install it by typing:
sudo apt install libav-tools
```
```
$ grep -rF '#define LIBAVFORMAT_VERSION' /usr/include/libavformat/
grep: /usr/include/libavformat/: No such file or directory
```
```
$ grep -rF '#define LIBAVFORMAT_VERSION' /usr/include/x86_64-linux-gnu/libavformat
/usr/include/x86_64-linux-gnu/libavformat/version.h:#define LIBAVFORMAT_VERSION_MAJOR  57
/usr/include/x86_64-linux-gnu/libavformat/version.h:#define LIBAVFORMAT_VERSION_MINOR  25
/usr/include/x86_64-linux-gnu/libavformat/version.h:#define LIBAVFORMAT_VERSION_MICRO 100
/usr/include/x86_64-linux-gnu/libavformat/version.h:#define LIBAVFORMAT_VERSION_INT AV_VERSION_INT(LIBAVFORMAT_VERSION_MAJOR, \
/usr/include/x86_64-linux-gnu/libavformat/version.h:#define LIBAVFORMAT_VERSION     AV_VERSION(LIBAVFORMAT_VERSION_MAJOR,   \
```

**Comment by grray** [comment]
Should I install libav-tools and rerun `avconv -version`?

**Comment by f0k** [comment]
> Should I install libav-tools

No, musly should work both with ffmpeg and avconv. I'll look into the version checks.

**Comment by f0k** [comment]
> I'll look into the version checks.

The version string is parsed correctly, the problem seems to be the new location of the header files:
https://github.com/dominikschnitzer/musly/blob/master/cmake/FindLibAV.cmake#L54
I'd appreciate any PR fixing this without breaking the current code. Maybe add a second search that's only called when the first one fails. Or maybe search for the include files first and derive the root directory from that. Or maybe there's something more elegant. You can assume that I'm not much more knowledgeable in CMake than you.

I don't see why it can't find `AVCodecParameters` on compilation, though. This was introduced [in libav's libavcodec 57.14.0](https://lists.libav.org/pipermail/libav-commits/2016-February/018029.html) and [in ffmpeg's libavcodev 57.14.0](https://github.com/FFmpeg/FFmpeg/commit/998e1b8f521b73e1ed3a13caaabcf79eb401cf0d), while you have libavcodec 57.24.102. Is there another header in your system that it includes instead? Does `grep -F 'AVCodecParameters' /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h` yield anything?

**Comment by grray** [comment]
#34 After this it says
```
-- Found LibAV: /usr/include/x86_64-linux-gnu (found suitable version "3.0.7", minimum required is "0.8") found components:  avcodec avformat avutil 
```
And I can start compilation. If i fix AVCodecParameters error then it builds and run ok

>Does grep -F 'AVCodecParameters' /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h yield anything?

No, nothing. It seems like this change is somehow in FFmpeg 3.1 while I have ffmpeg 3.0. Commit doesn't have 3.0 tag. It's weird. Also this https://www.ffmpeg.org/doxygen/3.1/structAVCodecParameters.html and https://www.ffmpeg.org/doxygen/3.0/structAVCodecParameters.html with 3.0 in url gives 404

**Comment by f0k** [comment]
> No, nothing. It seems like this change is somehow in FFmpeg 3.1 while I have ffmpeg 3.0. Commit doesn't have 3.0 tag.

Hmm, interesting. So AVCodecParameters was meant to be [introduced in libavcodev 57.14.0](https://github.com/FFmpeg/FFmpeg/commit/998e1b8f521b73e1ed3a13caaabcf79eb401cf0d), but now it's not in ffmpeg 3.0 ([libavcodec 57.24.102](https://github.com/FFmpeg/FFmpeg/blob/n3.0/libavcodec/version.h#L31)), only in ffmpeg 3.1 ([libavcodec 57.48.101](https://github.com/FFmpeg/FFmpeg/blob/n3.1/libavcodec/version.h#L30])).
Okay, looking at the [change log](https://github.com/FFmpeg/FFmpeg/blob/n3.1/doc/APIchanges#L64) instead, it says `2016-xx-xx - lavc 57.33.100 / 57.14.0 - avcodec.h`. So we'd need to change the [`#if` conditional](https://github.com/dominikschnitzer/musly/blob/master/libmusly/decoders/libav.cpp#L176) to check for libavcodec 57.33.100 instead. We also need to check what's the correct version in libav's libav, though.

**Comment by f0k** [comment]
> We also need to check what's the correct version in libav's libav, though.

For libav, it seems to be 57.14.0: https://github.com/libav/libav/blob/master/doc/APIchanges#L182
We can use the micro version to distinguish between libav and ffmpeg, but this seems all a little brittle. It's a very annoying situation with these two forks.

**Comment by f0k** [comment]
Somebody did it like this: https://github.com/MaxKellermann/MPD/blob/master/src/decoder/plugins/FfmpegDecoderPlugin.cxx#L645-L684
But this looks like when having bad luck with the versions it could run into a situation where it allocates a context and not calls avcodec_parameters_to_context on it.

**Comment by grray** [comment]
If there is any way to check ffmpeg version, than we could leave 57.14.0 check and just add requirement ffmpeg >= 3.1 for AVCodecParameters code.

**Comment by f0k** [comment]
I think we'd need something like: If ((microversion < 100) and (version >= 57.14)) or (version >= 57.33). This should cater for the fact that ffmpeg merged this later than avconv (if I understand correctly).

**Comment by grray** [comment]
I'm sorry. I missed your comment, and then new Ubuntu release happened, so I don't have ffmpeg 3.0 anymore. Master builds fine in ubuntu 17.04.

**Comment by f0k** [comment]
Okay. Guess I'll add the modification anyway.
